import React, { useCallback, useEffect, useState } from 'react';
import Head from 'next/head';
import axiosClient from '@/libraries/axiosClient';
import Link from 'next/link';

function Products(props) {
  const [products, setProducts] = useState([]);
  // Call API

  const getProducts = useCallback(async () => {
    try {
      const res = await axiosClient.get('/products');
      setProducts(res.data.payload);
    } catch (error) {
      console.log(error);
    }
  }, []);

  useEffect(() => {
    getProducts()
  }, [getProducts]);

  return (
    <>
      <Head>
        <title>Hello</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
        products.length > 0 ? (
          <div style={{display: 'flex', flexDirection: 'column'}}>
            {products.map((p) => <Link key={p._id} href={`/products/${p._id}`}><h1>{p.name}</h1></Link>)}
          </div>
        ) : <small>Không có sản phẩm</small>
      }
    </>
  );
}

export default Products;
